input/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'input'

urlpatterns = [
    
    path('', views.main, name='main'),
    path('input/', views.input, name='input'),
    path('output/<int:id>/', views.output, name='output'),
    path('wrong/<int:id>/', views.if_wrong, name='wrong'),
    path('graph/', views.graph, name='graph'),

]

petdictionary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('input.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

input/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django_base64field.fields import Base64Field
# Create your models here.

# 이미지 파일 업로드 모델

class Image(models.Model):
    # 이미지 파일 업로드
    imgfile = models.ImageField(null=False, upload_to="input/", blank=False)
    
    
class InputModel(models.Model):
    # 품종이름   
    img_data = Base64Field(max_length=900000, blank=True, null=True)
    # 사물인식 파일(base64 인코딩)
    species = models.CharField(max_length=20, blank=True, null=True)
    # 종
    breed = models.CharField(max_length=20, blank=True, null=True)
    # 품종
    search_link = models.CharField(max_length=500, blank=True, null=True)
    # 서치링크
    correct = models.BooleanField(default=True)
    # 검색된 품종 이름
    pet_result = models.CharField(max_length=20)
    # 품종이름이 다를때 (기존 이미지 분석의 결과값)


    

    


    

input/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import search, inference
from .models import InputModel, Image
from googletrans import Translator


# Create your views here.

def main(request):
    return render(request, 'main.html')
    

def input(request):
    if request.method == 'GET':
        return render(request, 'input.html')
    
    elif request.method == 'POST':
        img = request.FILES.get("imgfile")
        if img: 
            giveimage = Image.objects.create(imgfile=img)

            
            img_loc = giveimage.imgfile
            media_loc = 'media/' + str(img_loc)
            output_data = inference.inference(media_loc)

            if output_data==1:
                return render(request, 'input.html',{'error' : '이미지 인식 오류, 이미지를 다시 등록해주세요'})

        #모델 저장
            my_search = InputModel()
            my_search.img_data = output_data['img_data']
            my_search.species = output_data['species']
            my_search.breed = output_data['breed']
            my_search.search_link = output_data['search_link']
            my_search.save()
       
            return redirect(f'/output/{my_search.id}')
        else:
            return render(request, 'input.html',{'error' : '이미지가 등록되지 않았습니다'})



def output(request, id):
    my_pet = InputModel.objects.get(id=id)

    if request.method == 'GET':
        
        
        species = my_pet.species
        breed = my_pet.breed
        search_link = my_pet.search_link
        img_data = my_pet.img_data
       
        trans = Translator() 
        result = trans.translate(species, src='en', dest='ko')
        species_ko = result.text

        search_data = f'{breed}'
        context = search.serch_cat(search_data) 
        if context['none']== True:
            search_data = f'{breed} {species}'
            context = search.serch_cat(search_data)  
       
        info = {
            'species_ko':species_ko,
            'breed':breed,
            'search_link':search_link,
            'img_data':img_data,
            'context':context,
            'id':id,
        }

        return render(request, 'output.html', info)

    elif request.method == 'POST':
        id=id
        result = request.POST.get('result') # 검색 정확도 설문 결과
        if result == 'yes':
             my_pet.correct = True
             my_pet.save()
             return redirect('/graph')
        
        elif result == 'no':
            my_pet.correct = False
            my_pet.save()
            return redirect(f'/wrong/{id}') 


def if_wrong(request, id):
    
    if request.method == 'POST':
        search_data = request.POST.get("search")
        context=search.serch_cat(search_data)

        my_pet = InputModel.objects.get(id=id)
       
        my_pet.pet_result = search_data   # 재검색 시 사용한 keyword
        my_pet.save()   # 재검색 결과를 DB에 저장

        return render(request, 'if_wrong.html', context)

    elif request.method == 'GET':
        return render(request, 'if_wrong.html', {'id':id})

  



def graph(request):
    if request.method == 'GET':

        yes = InputModel.objects.filter(correct=1).count()
        total = InputModel.objects.all().count()
        if total == 0 :
            percent = 0
        else:
            percent = int((yes/total)*100)
        
        return render(request, 'accuracy_graph.html',{'data':percent})

input/templates/accuracy_graph.html
<!DOCTYPE html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</head>

<style>
    body {
        display: flex;
        height: 100vh;
        width: 100vw;
        justify-content: center;
        flex-wrap: nowrap;
        align-items: center;
        box-sizing: border-box;
        background: #EFDEEE;

    }

      .container{
        display: flex;
        justify-content: center;
        align-items: center;
        height: 90vh;
        flex-direction: column;
        padding: 2em;
        width: 100%;
        
        background: #EFDEEE;
      
      }
      
      section{
        flex-direction: row;
        background-color: white;
        padding: 1em 2em;
        margin: 5%; 
        text-align: center;
        height: 600px;
        box-shadow: 0 0.2em 0.45em 0.1em rgba(0,0,0, 0.4);
        
        width: 90%;
        max-width: 50em;
        
        
    }
      
    h1{
        margin-bottom: 0;
        font-weight: bold;
        font-size: 30px;
    }
      
    h2{
        margin-bottom: 3rem;
        font-weight: bold;
        font-size: 20px;
    }

    .pie-chart {
        position: relative;
        display:inline-block;
        width: 200px;
        height: 200px;
        border-radius: 50%;
        transition: 0.3s;
      }
      span.center{
        background: #fff;
        display : block;
        position: absolute;
        top:50%; left:50%;
        width:100px; height:100px;
        border-radius: 50%;
        text-align:center; 
        line-height: 100px;
        font-size:30px;
         transform: translate(-50%, -50%);
      }

      {% comment %} 그래프 {% endcomment %}

      .info_section {
        padding: 30px;
        background: #fafafa;
        margin: 15px 0;
        border-radius: 8px;
        display: flex;
        align-items: center;
        max-width: 960px;
      }
      .graph-circle {
        position: relative;
      }
      .circle-graph-container {
        position: relative;
        display: flex;
      }
      .circle-graph {
        margin: 0 15px;
        position: relative;
        width: 50%;
        line-height: 1.2 !important;
        -webkit-transition: all 0.3s ease-in-out;
        -o-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        font-family: 'Roboto', sans-serif;
        font-weight: 300;
      }
      canvas {
        position: absolute;
        top: 0px;
      }
      .stats {
        width: 100% !important;
        margin: 0 30px;
        display: flex;
        flex-direction: column;
        justify-content: center;
      }
      .stats p {
        line-height: 1.2;
        font-size: 21px;
        color: #545454;
        font-family: 'Roboto', sans-serif;
        font-weight: 300;
      }
      span.info_section_wordHighlight {
        color: #003A79;
        font-weight: 600;
      }

      


    
    
      
</style>

<script>
    $(window).ready(function(){
        draw({{data}}, '.pie-chart1', '#ccc');
     });
     
     function draw(max, classname, colorname){
        var i=1;
         var func1 = setInterval(function(){
           if(i<max){
               color1(i,classname,colorname);
               i++;
           } else{
             clearInterval(func1);
           }
         },10);
     }
     function color1(i, classname,colorname){
        $(classname).css({
             "background":"conic-gradient("+colorname+" 0% "+i+"%, #ffffff "+i+"% 100%)"
        });
     }

    



   
</script>


<body>


    <div class="container">
    
        <section>
            <h2 style="margin-top:20px;">정확도 비교</h2>
            <div class="pie-chart pie-chart1"><span class="center">{{data}}%</span></div>
            <h2 style="margin-top:80px;">이용해 주셔서 감사합니다!</h2>
            <button type="button" class="btn btn-outline-secondary" onClick="location.href='/';" >돌아가기</button>

                            
        </section>
        
        

    </div>

    



</body>


</html>

{% comment %}  {% endcomment %}

input/templates/if_wrong.html
<!DOCTYPE html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/477c22bae2.js" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
  

</head>
<style>
    @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,700);

    body {
        display: flex;
        height: 100vh;
        width: 100vw;
        justify-content: center;
        flex-wrap: nowrap;
        align-items: center;
        box-sizing: border-box;
        background: #EFDEEE;
    }
    main {
        flex-direction: column;
        background-color: white;
        width: 800px;
        height: auto;
        margin: 40px auto;
        padding: 10px 0;
        box-shadow: 0 3px 5px rgba(0,0,0,0.3);
    }
    h2 {
        text-align: center;
    }
    p {
        font-size: 13px;
    }

    .btn-select{
        margin: 0px auto;
        width: auto;
        height: auto;
        text-align:center;
        padding: 10px;

    }

    .search {
        width: 100%;
        position: relative;
        display: flex;
    }

    .searchTerm {
        
        width: 100%;
        border: 3px solid #00B4CC;
        border-right: none;
        padding: 5px;
        height: 36px;
        border-radius: 5px 0 0 5px;
        outline: none;
        color: #9DBFAF;
    }

    .searchTerm:focus{
        color: #00B4CC;
    }

    .searchButton {
        width: 40px;
        height: 36px;
        border: 1px solid #00B4CC;
        background: #00B4CC;
        text-align: center;
        color: #fff;
        border-radius: 0 5px 5px 0;
        cursor: pointer;
        font-size: 20px;
    }


    .wrap{
        width: 80%;
       
        margin:10px auto 10px auto;
    }

    .post-image{
        width: 100%;
        height: 500px;
        object-fit: cover;
    }
   
    h4{
        font-size:20px;
        font-weight: bold;
    }

    
    .text_info{

    }
    .show_none{
        text-align:center;
        padding: 20px;
        border: dotted 5px;
        
    }

    .show_none h4{
        margin-bottom:20px;
    }

    h6{
        font-weight: bold;
    }
    
    .informations {
        background-color: #E2E2E2; 
        padding:10px; 
        margin-bottom:10px;  
        border-radius: 10px;
    }

    
    
      
</style>

<script>

   
   
</script>


<body>
    <main>
        <div class="container">
            {% if not name %}
                <section>
                    <h2>Search Pet</h2>
                        <form method="POST" active="{% url 'input:wrong' id %}">
                            {% csrf_token %}
                            <div class="wrap" style="border:1px solid black">
                                <div class="search">
                                <input type="text" class="searchTerm" placeholder="What are you looking for?" name="search">
                                <button type="submit" class="searchButton">
                                    <i class="fa fa-search"></i>
                                </button>
                                </div>
                            </div>
                            <hr>
                            
                        </form>
                </section>
                
                
                </div>
                <h4 class="btn-select">찾으셨던 pet 종을 입력하고 버튼을 눌러주세요</h4>
                <div class="btn-select">
                    <h6>정확도 확인하기</h6>
                    <button type="button" class="btn btn-outline-info" onClick="location.href='/graph';">확인</button>
                </div>
        
            {% elif name and none == False %}
                <img src="{{ img }}" class="post-image" alt="이미지 없음">
            
                <section style="padding:30px">
                    <h4 style="text-align:center;">{{ name }}</h4>
                    <hr>
                    <h3 style="margin-top:20px;">검색 결과</h3>
                    <div class="search_info">
                        
                        <div class="informations">
                            {% for data in info %}
                            {{ data }}</br>
                            {% endfor %}          
                        </div>
                        내용 : {{ text }}
                    </div>
                </section>
                <div class="btn-select">
                    <h6>정확도 확인하기</h6>
                    <button type="button" class="btn btn-outline-info" onClick="location.href='/graph';">확인</button>
                </div>
            
            {% elif name and none == True %}
            <section>
                <h2>Search Pet</h2>
                    <form method="POST" active="/wrong/">
                        {% csrf_token %}
                        <div class="wrap" style="border:1px solid black">
                            <div class="search">
                            <input type="text" class="searchTerm" placeholder="What are you looking for?" name="search">
                            <button type="submit" class="searchButton">
                                <i class="fa fa-search"></i>
                            </button>
                            </div>
                        </div>
                        <hr>
                        <div class="show_none">
                            <h4>해당 검색은 현재 데이터가 없습니다.</h4>
                            <p>구글 검색 결과 보기. <span style="cursor: pointer; color: blue;"  onclick="window.open('{{ url }}', 'window_name', 'width=1200, height=800, location=no, status=no, scrollbars=yes');" >{{ name }}</span></p>
                            
                        </div>
                        <div class="btn-select">
                            <h6>정확도 확인하기</h6>
                            <button type="button" class="btn btn-outline-info" onClick="location.href='/graph';">확인</button>
                        </div>
                        
                        
                    </form>
            </section>

            
            {% endif %}

    </main>
   
</body>

</html>

input/templates/input.html
<!DOCTYPE html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</head>


<style>
    body {
        display: flex;
        height: 100vh;
        width: 100vw;
        justify-content: center;
        flex-wrap: nowrap;
        align-items: center;
        box-sizing: border-box;
        background: #EFDEEE;

    }

      .container{
        display: flex;
        justify-content: center;
        align-items: center;
        height: 90vh;
        flex-direction: column;
        padding: 2em;
        width: 100%;
        background: #EFDEEE;
      
      }
      
      section{
        flex-direction: row;
        background-color: white;
        padding: 1em 2em;
        margin: 5%; 
        text-align: center;
        box-shadow: 0 0.2em 0.45em 0.1em rgba(0,0,0, 0.4);
        
        width: 90%;
        max-width: 50em;
        
        
    }
      
    h1{
        margin-bottom: 0;
        font-weight: bold;
        font-size: 30px;
    }
      
    h2{
        margin-bottom: 3rem;
        font-weight: bold;
        font-size: 20px;
    }

    .image_container{
        margin-bottom:10px
        width:100%;
        height: 500px;
    }

    .error-text{
        max-width: 50em;
        width:90%;
        text-align:center;
    }
    #back{    
        position: absolute;    
        z-index: 100;    
        background-color: #000000;    
        display:none;    
        left:0;    
        top:0;
    } 
    #loadingBar{    
        position:absolute;    
        left:50%;    
        top: 40%;    
        display:none;    
        z-index:200;
    }

</style>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
          var reader = new FileReader();
          reader.onload = function(e) {
            document.getElementById('preview').src = e.target.result;
          };
          reader.readAsDataURL(input.files[0]);
        } else {
          document.getElementById('preview').src = "";
        }
    }
    function FunLoadingBarStart() {    
        var backHeight = $(document).height();               	//뒷 배경의 상하 폭    
        var backWidth = window.document.body.clientWidth;		//뒷 배경의 좌우 폭     
        var backGroundCover = "<div id='back'></div>";			//뒷 배경을 감쌀 커버    
        var loadingBarImage = '';								//가운데 띄워 줄 이미지     
        loadingBarImage += "<div id='loadingBar'>";    
        loadingBarImage += "<div class='spinner-border text-info' role='status'>"; //로딩 바 이미지    
        loadingBarImage += "<span class='visually-hidden'>Loading...</span>";
        loadingBarImage += "</div>";
        loadingBarImage += "</div>";     
        $('body').append(backGroundCover).append(loadingBarImage);      
        $('#back').css({ 'width': backWidth, 'height': backHeight, 'opacity': '0.3' });    
        $('#back').show();     
        $('#loadingBar').show();}
</script>


<body>
    <div class="container">
        
        <header>
            <h1>Search Pet</h1>
        </header>
    
        <section>
            <h2>반려동물의 이미지를 업로드 해주세요</h2>

            
                <form action="/input/" method="POST" enctype="multipart/form-data" novalidate>

                
                    {% csrf_token %}
                    <div class="mb-3">
                        <input class="form-control" accept='image/*' type="file" onchange="readURL(this);" name="imgfile">                   
                    </div>
                    <button type="submit" class="btn btn-outline-secondary" onclick="FunLoadingBarStart()">확인하기</button>

                </form>
        </section>
        {% if error %}
            <div class="alert alert-danger error-text" role="alert">
                {{ error }}
            </div>
        {% endif %}
        
        <img id="preview" class="image_container">
    </div>
    

</body>


</html>

input/templates/output.html
<!DOCTYPE html>
<header>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/477c22bae2.js" crossorigin="anonymous"></script>

</header>
<style>
    @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,700);

    body {
        display: flex;
        height: 100vh;
        width: 100vw;
        justify-content: center;
        flex-wrap: nowrap;
        align-items: center;
        box-sizing: border-box;
        background: #EFDEEE;

    }
    main {
        background: #EEE;
        width: 800px;
        height: auto;
        margin: 20px auto;
        padding: 10px 0;
        box-shadow: 0 3px 5px rgba(0,0,0,0.3);
    }
    h2 {
        text-align: center;
    }
    p {
        font-size: 13px;
    }
    input {
        display: none;
        visibility: hidden;
    }
    label {
        display: block;
        padding: 0.5em;
        text-align: center;
        border-bottom: 1px solid #CCC;
        color: #666;
    }
    label:hover {
        
    }
    label::before {
        font-family: Consolas, monaco, monospace;
        font-weight: bold;
        font-size: 15px;
        content: "+";
        vertical-align: text-top;
        display: inline-block;
        width: 20px;
        height: 20px;
        margin-right: 3px;
        background: radial-gradient(ellipse at center, #CCC 50%, transparent 50%);
    }
    #expand {
        width:auto;
        height: 100%;
        
        transition: height 0.5s;
        background: url(https://helpx.adobe.com/content/dam/help/en/photoshop/using/quick-actions/remove-background-before-qa1.png);
        color: #FFF;
    }
    section {
        padding: 0 20px;
    }
    #toggle:checked ~ #expand {
        height: 400px;
    }
    #toggle:checked ~ label::before {
        content: "-";
    }
    .btn-select{
        margin: 0px auto;
        
        width: auto;
        height: auto;
        text-align:center;
        padding: 20px

    }
    button{
        width:90px;
        margin:10px 10px;
    }

    h4{
        font-size:18px;
        font-weight: bold;
    }
    .post-image{
        height: 500px;
        text-align: center;
    }
    .post-image img{
        height: 100%;
        width: auto;
    }

    .informations {
        background-color: #E2E2E2; 
        padding:10px; 
        margin-bottom:10px;  
        border-radius: 10px;
    }

    
    
      
</style>

<script>
    
   
</script>


<body>
    <main>

        <h2>검색하신 {{ species_ko }}는 {{ breed }}입니다.</h2>
        <input id="toggle" type="checkbox" checked>

        <div class="post-image">
        <img src="data:image/jpeg;base64,{{ img_data }}" alt="" >
        </div>
        <section>
          <h3 style="margin-top:20px;">검색 결과</h3>
          {% if context.info %}
            <div class="informations">
                {% for data in context.info %}
                {{ data }}</br>
                {% endfor %}
            </div>
            내용: {{ context.text }}
          {% endif %}
            {% if context.none == True %}
            <div class="informations" style="text-align:center;">
                <h4>해당 검색은 현재 데이터가 없습니다.</h4>    
                <p>구글 검색 결과 보기. <span style="cursor: pointer; color: blue;"  onclick="window.open('{{ context.url }}', 'window_name', 'width=1200, height=800, location=no, status=no, scrollbars=yes');" >{{ breed }}</span></p>
            </div>
            {% endif %}
            
        </section>


        <form action="{% url 'input:output' id %}" method="POST">
            {% csrf_token %}
            <div class="btn-select">
                <h4>원하시는 품종이 맞으신가요?</h4>
                    <button type="submit" class="btn btn-success" value="yes" name="result">예</button>
                    <button type="submit" class="btn btn-danger" value="no" name="result">아니요</button>
            </div>
        </form>
        
    </main>

</body>

</html>